sam_admin_homepage:
    path:     /
    defaults: { _controller: SAMAdminBundle:Admin:index }

sam_admin_projectpage:
    path:     /project
    defaults: { _controller: SAMAdminBundle:Project:addProject }

sam_admin_certifpage:
    path:     /certification
    defaults: { _controller: SAMAdminBundle:Certification:addCertif }

sam_admin_followpage:
    path:     /follow-project
    defaults: { _controller: SAMAdminBundle:FollowProject:follow }
