<?php

namespace SAM\CoreBundle\Repository;

/**
 * FollowProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
